INSERT OR REPLACE INTO games (name, develoepr, publisher, description) VALUES ('Rocket League', 'Psyonix LLC', 'Psyonix LLC', 'Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition.<br>Download and compete in the high-octane hybrid of arcade-style soccer and vehicular mayhem! customize your car, hit the field, and compete in one of the most critically acclaimed sports games of all time! Download and take your shot!<br>Hit the field by yourself or with friends in 1v1, 2v2, and 3v3 Online Modes, or enjoy Extra Modes like Rumble, Snow Day, or Hoops. Unlock items in Rocket Pass, climb the Competitive Ranks, compete in Competitive Tournaments, complete Challenges, enjoy cross-platform progression and more! The field is waiting. Take your shot!');
INSERT OR REPLACE INTO games (name, developer, publisher, description) VALUES ('Fortnite', 'Epic Games', 'Epic Games', '<h2>Battle. Build. Create.<h2><br>Fortnite is the free, always evolving, multiplayer game where you and your friends battle to be the last one standing or collaborate to create your dream Fortnite world. Play both Battle Royale and Fortnite Creative for FREE. Download now and jump into the action. This download also gives you a path to purchase the Save the World co-op PvE campaign.');
INSERT OR REPLACE INTO games (name, developer, publisher, description) VALUES ('ABZU', 'Giant Squid', '305 Games', 'Immerse yourself in a vibrant ocean world full of mystery and bursting with color and life. Perform fluid acrobatics as the Diver using graceful swimming controls. Discover hundreds of unique species based on real creatures and form a powerful connection with the abundant sea life. Interact with schools of thousands of fish that procedurally respond to you, each other, and predators. Linger in epic seascapes and explore aquatic ecosystems modeled with unprecedented detail. Descend into the heart of the ocean where ancient secrets lie forgotten. But beware, dangers lurk in the depths.');
INSERT OR REPLACE INTO games (name, developer, publisher, description) VALUES ('AER', 'Forgotten Key', 'Daedalic Entertainment', 'Transform into a bird and fly to explore and experience a vibrant world of floating islands in the sky. Venture down into lost ancient ruins where each step leads you closer to the end of the world.<br>The gods of old are forgotten, lost in the events that shattered the world, leaving only fragments of islands in the sky. This mystic world of endless skies, colorful islands and ancient ruins is in danger of falling into darkness. As one of the last few shapeshifters, you are sent on a pilgrimage to the Land of Gods. Uncover the secrets that will help save reality itself.<br>Features<br>Fly and explore by transforming into a bird at will<br>A large open world of hidden secrets and new discoveries<br>A pilgrimage of mysteries, puzzles and temples<br>Strong focus on atmosphere and aesthetics with a vibrant minimalist art style');
-- INSERT OR REPLACE INTO games (name, developer, publisher, description) VALUES ('APE OUT', 'Gabe Cuzzillo, Bennett Foddy, Matt Boch', 'Devolver Digital', 'APE OUT is a wildly intense and colorfully stylized smash ‘em up about primal escape, rhythmic violence, and frenetic jazz.<br>Build up nearly unstoppable momentum and use your captors as both weapons and shields to crush everyone on your procedurally generated path to freedom.<br>Grab and Smash<br>Unleash your primal instincts and incredible strength to overpower your captors. Hold them steady to create a human shield, smash their feeble bodies into walls, or throw one into another in a violent explosion of humanity.<br>Dynamic Soundtrack<br>Find your rhythm in the chaos as a dynamic soundtrack of drums, cymbals, and decapitations drive the action to the edge of mayhem.<br>Stylish Escape<br>Embrace bold colors and a dazzling perspective as you rush through corridors, open areas, and twisting labyrinths on a mad dash for freedom. Overcome all manner of opposition, nefarious traps, and breakable obstacles to find each exit and escape captivity.');
INSERT OR REPLACE INTO games (name, developer, publisher, description) VALUES
INSERT OR REPLACE INTO games (name, developer, publisher, description) VALUES
INSERT OR REPLACE INTO games (name, developer, publisher, description) VALUES
INSERT OR REPLACE INTO games (name, developer, publisher, description) VALUES
INSERT OR REPLACE INTO games (name, developer, publisher, description) VALUES